package towerprint

import (
	"reflect"
	"testing"
	"time"
)

// All expected values in this file were generated by running the
// original Python (QUEENSALLYONLINEBOOKOFMAGIFICATIONANDUNICOR/
// gpt-2/pemdas.py functions, which are pure string manipulation with no
// TF dependency) under python3, or copied from executed notebook cell
// outputs in TOYBOK/COR.ipynb.

func TestSquish(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"bananna", "BANANA"},
		{"BANANNA", "BANANA"},
		{"NOW THERE ARE ONLY BIRDS left outside the gate for the public to see",
			"NOWTHEREAREONLYBIRDSLEFTOUTSIDETHEGATEFORTHEPUBLICTOSE"},
		{"NOW WE ARE ONLY BIRDS", "NOWEAREONLYBIRDS"},
		{"STILLIORIALS", "STILIORIALS"},
		{`                    - WHO ELSE SEEN THE LEPRECHAUN?SAY "YEAH"!`,
			"WHOELSESENTHELEPRECHAUNSAYEAH"},
		{"QUEENSALLYONLINEBOOKOFMAGIFICATIONANDUNICOR",
			"QUENSALYONLINEBOKOFMAGIFICATIONANDUNICOR"},
		// Dropped characters do not reset the duplicate window.
		{"a a", "A"},
		{"Mississippi 122 __ !!", "MISISIPI12_"},
		{"", ""},
		{"?!.,", ""},
	}
	for _, tt := range tests {
		if got := Squish(tt.in); got != tt.want {
			t.Errorf("Squish(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestU2V(t *testing.T) {
	tests := []struct {
		in, want string
	}{
		{"rainboW", "RAINBOV"},
		{"dinosaur", "DINOSAVR"},
		{"QUuWw", "QVVVV"},
	}
	for _, tt := range tests {
		if got := U2V(tt.in); got != tt.want {
			t.Errorf("U2V(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestTower(t *testing.T) {
	tests := []struct {
		in    string
		width int
		want  []string
	}{
		// Notebook cell 26: trxtwr("dinosaur", 3).
		{"dinosaur", 3, []string{"DIN", "OSA", "URX"}},
		{"NOW THERE ARE ONLY BIRDS", 3,
			[]string{"NOW", "THE", "REA", "REO", "NLY", "BIR", "DSX"}},
		{"NOW WE ARE ONLY BIRDS", 3,
			[]string{"NOW", "EAR", "EON", "LYB", "IRD", "SXX"}},
		{"STILLIORIALS", 3, []string{"STI", "LIO", "RIA", "LSX"}},
		{"QUEENSALLYONLINEBOOKOFMAGIFICATIONANDUNICOR", 3,
			[]string{"QUE", "NSA", "LYO", "NLI", "NEB", "OKO", "FMA",
				"GIF", "ICA", "TIO", "NAN", "DUN", "ICO", "RXX"}},
		{"", 3, nil},
	}
	for _, tt := range tests {
		if got := Tower(tt.in, tt.width); !reflect.DeepEqual(got, tt.want) {
			t.Errorf("Tower(%q, %d) = %v, want %v", tt.in, tt.width, got, tt.want)
		}
	}
}

// TestTowerVOIDONX pins the port against the repo's saved real-session
// artifact (VOIDONX): GPT-2 output lines whose tower renderings were
// captured verbatim. VOIDONX shows only the complete leading rows before
// GPT-2's own continuation takes over, so we compare prefixes.
func TestTowerVOIDONX(t *testing.T) {
	tests := []struct {
		in         string
		wantPrefix []string
	}{
		{"NOW THERE ARE ONLY BIRDS",
			[]string{"NOW", "THE", "REA", "REO", "NLY", "BIR"}},
		{"NOW WE ARE ONLY BIRDS",
			[]string{"NOW", "EAR", "EON", "LYB", "IRD"}},
		{"STILLIORIALS", []string{"STI", "LIO", "RIA"}},
	}
	for _, tt := range tests {
		got := Tower(tt.in, TowerWidth)
		if len(got) < len(tt.wantPrefix) ||
			!reflect.DeepEqual(got[:len(tt.wantPrefix)], tt.wantPrefix) {
			t.Errorf("Tower(%q) = %v, want prefix %v", tt.in, got, tt.wantPrefix)
		}
	}
}

func TestMatrixTower(t *testing.T) {
	want := []string{"W", "A", "S", "H", "I", "N", "G", "T", "O", "N", "D", "C"}
	if got := MatrixTower("WASHINGTON DC"); !reflect.DeepEqual(got, want) {
		t.Errorf("MatrixTower(WASHINGTON DC) = %v, want %v", got, want)
	}
}

func TestClassicTower(t *testing.T) {
	tests := []struct {
		in   string
		want []string
	}{
		{"WASHINGTON DC", []string{"WAS", "HIN", "GTO", "NDC"}},
		// PRINTWR pads a lone trailing character with "XZ", not "XX".
		{"APPLE", []string{"APL", "EXZ"}},
		{"BANANNA", []string{"BAN", "ANA"}},
		{"NOW WE ARE ONLY BIRDS",
			[]string{"NOW", "EAR", "EON", "LYB", "IRD", "SXZ"}},
		{"STILLIORIALS", []string{"STI", "LIO", "RIA", "LSX"}},
	}
	for _, tt := range tests {
		if got := ClassicTower(tt.in); !reflect.DeepEqual(got, tt.want) {
			t.Errorf("ClassicTower(%q) = %v, want %v", tt.in, got, tt.want)
		}
	}
}

func TestTowerString(t *testing.T) {
	if got := TowerString([]string{"DIN", "OSA", "URX"}); got != "DIN\nOSA\nURX\n" {
		t.Errorf("TowerString = %q", got)
	}
	if got := TowerString(nil); got != "" {
		t.Errorf("TowerString(nil) = %q, want empty", got)
	}
}

func TestCodzeify(t *testing.T) {
	tests := []struct {
		word                       string
		azDec, azBin, zaDec, zaBin string
	}{
		// Notebook cell 13: codzeifyWord("SALLY").
		{"SALLY", "20330", "100111101101010", "71661", "10001011111101101"},
		{"APPLE", "7734", "1111000110110", "12265", "10111111101001"},
		{"NOWEAREONLYBIRDS",
			"5664014653010132",
			"10100000111110110010000101101011001010011000011010100",
			"4335105346101067",
			"1111011001101100000101011110001101111101111101001011"},
		// Long input: exceeds int64/uint64, exercises big.Int parity
		// with Python arbitrary-precision ints.
		{"NOWTHEREAREONLYBIRDSLEFTOVTSIDETHEGATEFORTHEPVBLICTOSE",
			"566374140146530101323453653203437460345613747513023624",
			"10111101001110010001110100110011010010000101000011110110111010110100111011111010101011101000101101110101111110010101110000001001000101000101011000011001011110100010101110010001000",
			"433625051053461010676546346716562531654306252406176375",
			"10010000110111110100100110011000100010010011001101110010010010100001111010110010110011100100111111011000110111111010111101010100101011000010010110100110000101010001011101001110111"},
	}
	for _, tt := range tests {
		got, err := Codzeify(tt.word)
		if err != nil {
			t.Fatalf("Codzeify(%q): %v", tt.word, err)
		}
		want := Codze{
			Word: tt.word,
			AZ:   Signature{Dec: tt.azDec, Bin: tt.azBin},
			ZA:   Signature{Dec: tt.zaDec, Bin: tt.zaBin},
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("Codzeify(%q) = %+v, want %+v", tt.word, got, want)
		}
	}
}

func TestCodzeifyErrors(t *testing.T) {
	if _, err := Codzeify(""); err == nil {
		t.Error("Codzeify(\"\") should error")
	}
	if _, err := Codzeify("R2D2"); err == nil {
		t.Error("Codzeify(R2D2) should error on digits")
	}
	if _, err := CodzeifyGrouped("A", 0); err == nil {
		t.Error("CodzeifyGrouped(A, 0) should error")
	}
}

// TestMagicCodeMatchesOriginalTable verifies the derived 3x8 grid
// coordinates against the hand-written magicVVVLookup table from
// TOYBOK/COR.ipynb cell 27 — proving the derivation is the table.
func TestMagicCodeMatchesOriginalTable(t *testing.T) {
	original := map[rune]string{
		'A': "20 07", 'B': "10 17", 'C': "00 27", 'D': "21 06",
		'E': "11 16", 'F': "01 26", 'G': "22 05", 'H': "12 15",
		'I': "02 25", 'J': "23 04", 'K': "13 14", 'L': "03 24",
		'M': "24 03", 'N': "14 13", 'O': "04 23", 'P': "25 02",
		'Q': "15 12", 'R': "05 22", 'S': "26 01", 'T': "16 11",
		'V': "06 21", 'X': "27 00", 'Y': "17 10", 'Z': "07 20",
	}
	for r, want := range original {
		got, ok := MagicCode(r)
		if !ok || got != want {
			t.Errorf("MagicCode(%q) = %q, %v; want %q", r, got, ok, want)
		}
	}
	// U and W normalize to V's code.
	for _, r := range "UuWw" {
		if got, ok := MagicCode(r); !ok || got != "06 21" {
			t.Errorf("MagicCode(%q) = %q, %v; want V's code", r, got, ok)
		}
	}
	if _, ok := MagicCode('7'); ok {
		t.Error("MagicCode('7') should not resolve")
	}
}

func TestMagicTower(t *testing.T) {
	// pemdas.py: trxtwrstr(magicVVVDecTower(trxtwr(U2V("dinosaur"), 3)))
	// with the pemdas variant's trailing space per code.
	rows := Tower(U2V("dinosaur"), 3)
	got, err := MagicTower(rows)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"21 06 02 25 14 13 ",
		"04 23 26 01 20 07 ",
		"06 21 05 22 27 00 ",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("MagicTower(dinosaur) = %v, want %v", got, want)
	}

	if _, err := MagicTower([]string{"A1C"}); err == nil {
		t.Error("MagicTower should error on non-letter rows")
	}
}

func TestCompute(t *testing.T) {
	fp, err := Compute("NOW WE ARE ONLY BIRDS")
	if err != nil {
		t.Fatal(err)
	}
	want := Fingerprint{
		Squished: "NOWEAREONLYBIRDS",
		Tower:    []string{"NOV", "EAR", "EON", "LYB", "IRD", "SXX"},
		Magic: []string{
			"14 13 04 23 06 21 ",
			"11 16 20 07 05 22 ",
			"11 16 04 23 14 13 ",
			"03 24 17 10 10 17 ",
			"02 25 05 22 21 06 ",
			"26 01 27 00 27 00 ",
		},
		Codze: Codze{
			Word: "NOWEAREONLYBIRDS",
			AZ: Signature{
				Dec: "5664014653010132",
				Bin: "10100000111110110010000101101011001010011000011010100",
			},
			ZA: Signature{
				Dec: "4335105346101067",
				Bin: "1111011001101100000101011110001101111101111101001011",
			},
		},
	}
	if !reflect.DeepEqual(fp, want) {
		t.Errorf("Compute = %+v, want %+v", fp, want)
	}

	if _, err := Compute("123 !!"); err == nil {
		t.Error("Compute should error with no letters")
	}
}

func TestFortMinute(t *testing.T) {
	tests := []struct {
		t    time.Time
		want int
	}{
		// Midnight: 0/864 - 1 = -1 (quirk preserved from the original).
		{time.Date(2026, 7, 16, 0, 0, 0, 0, time.UTC), -1},
		{time.Date(2026, 7, 16, 0, 14, 24, 0, time.UTC), 0}, // 864s exactly
		{time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC), 49}, // 43200/864-1
		{time.Date(2026, 7, 16, 23, 59, 59, 0, time.UTC), 98},
	}
	for _, tt := range tests {
		if got := FortMinute(tt.t); got != tt.want {
			t.Errorf("FortMinute(%v) = %d, want %d", tt.t, got, tt.want)
		}
	}
	if got := Seed(time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC)); got != "2026071649" {
		t.Errorf("Seed = %q, want 2026071649", got)
	}
}
